/*   Problem 2 Even Fibonacci numbers

Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
  find the sum of the even-valued terms.
*/


public class ProjectEuler
{

    
    public static void main(String[] args) {
     System.out.println(new P2().getSumFibonacci());
    }

}


class P2
{
    public long getSumFibonacci()
    {
        long sum=0;
        long prev=1;
        long cur=1;
        long fib=0;
        while( fib < 4000000)
        {   
            fib=prev+cur;
            prev=cur;
            cur=fib;
             if(fib % 2==0)
                sum+=fib;
        }
        return sum;
    }
}
